homepage: "https://accumulo.apache.org/"
language: jvm
primary_contact: "private@accumulo.apache.org"
auto_ccs:
  - "security@apache.org"
  - "dev@accumulo.apache.org"
main_repo: "https://github.com/apache/accumulo"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
