homepage: "https://ghidra-sre.org/"
language: jvm
primary_contact: "ghidra-fuzzing-maintainer@example.com"
auto_ccs: []
main_repo: "https://github.com/nationalsecurityagency/ghidra"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
