homepage: "https://kafka.apache.org/"
language: jvm
primary_contact: "security@kafka.apache.org"
auto_ccs:
  - "dev@kafka.apache.org"
main_repo: "https://github.com/apache/kafka"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
